# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flutt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='flutt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutter.User'),
        ),
    ]
