# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_auto_20160519_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutt',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
