# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0003_auto_20160519_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flutt',
            name='user',
        ),
        migrations.AddField(
            model_name='flutt',
            name='user_name',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
