# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0005_auto_20160519_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flutt',
            options={},
        ),
    ]
